services:

  booking:
    image: pradoo159/booking-service:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - hackanet

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "booking"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    networks:
      - hackanet

networks:
  hackanet:
    driver: bridge